[features]
resolution = true
skip-lint = false

[programs.localnet]
betting_contract = "BET1234567890abcdefghijklmnopqrstuvwxyz1234567"

[programs.devnet]
betting_contract = "TBD_AFTER_DEVNET_DEPLOYMENT"

[programs.mainnet]
betting_contract = "TBD_AFTER_DEPLOYMENT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"